currency: filter taskruns before sorting
Signed-off-by: Varsha GS <varsha.gs@ibm.com>

diff --git a/.tekton/.currency/currency-tasks.yaml b/.tekton/.currency/currency-tasks.yaml
--- a/.tekton/.currency/currency-tasks.yaml
+++ b/.tekton/.currency/currency-tasks.yaml
@@ -70,16 +70,20 @@ spec:
 
         cd /workspace        
         git clone https://oauth2:$GH_ENTERPRISE_TOKEN@github.ibm.com/instana/tracer-reports.git
-        if [ $? -eq 0 ]; then
-          cd tracer-reports
 
-          cp ../python-sensor/.tekton/.currency/docs/report.md ./automated/currency/python/report.md
-
-          git config user.name "Instanacd PAT for GitHub Enterprise"
-          git config user.email instana.ibm.github.enterprise@ibm.com
-          
-          git add .
-          
-          git commit -m "chore: Updated python currency report"
-          git push origin main
+        if [ $? -ne 0 ]; then
+            echo "The attempt to clone the tracer-reports repository failed, preventing the upload of python tracer currency report." >&2
+            exit 1
         fi
+        
+        cd tracer-reports
+
+        cp ../python-sensor/.tekton/.currency/docs/report.md ./automated/currency/python/report.md
+
+        git config user.name "Instanacd PAT for GitHub Enterprise"
+        git config user.email instana.ibm.github.enterprise@ibm.com
+        
+        git add .
+        
+        git commit -m "chore: Updated python currency report"
+        git push origin main
