fix(currency): skip push and exit pipeline when report generation fails
Signed-off-by: Varsha GS <varsha.gs@ibm.com>

diff --git a/.tekton/.currency/currency-tasks.yaml b/.tekton/.currency/currency-tasks.yaml
--- a/.tekton/.currency/currency-tasks.yaml
+++ b/.tekton/.currency/currency-tasks.yaml
@@ -42,6 +42,10 @@ spec:
         pip install -r resources/requirements.txt
 
         python scripts/generate_report.py
+        if [ $? -ne 0 ]; then
+            echo "Error occured while generating the python tracer currency report." >&2
+            exit 1
+        fi
         cat docs/report.md
 ---
 apiVersion: tekton.dev/v1beta1
